-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 12:23:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------
-- Hotel Schema

-- -----------------------------------------------------
-- Schema Hotel
--
-- Hotel Schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hotel` DEFAULT CHARACTER SET utf8 ;
USE `Hotel` ;

-- -----------------------------------------------------
-- Table `Hotel`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`State` (
  `StateID` INT NOT NULL,
  `State` VARCHAR(20) NOT NULL,
  `City` VARCHAR(20) NOT NULL,
  `Zip` CHAR(10) NOT NULL,
  PRIMARY KEY (`StateID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`Guest` (
  `GuestID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `StateID` INT NOT NULL,
  `Phone` CHAR(10) NOT NULL,
  PRIMARY KEY (`GuestID`),
  INDEX `fk_idx` (`StateID` ASC) VISIBLE,
  CONSTRAINT `fk`
    FOREIGN KEY (`StateID`)
    REFERENCES `Hotel`.`State` (`StateID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`RoomType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`RoomType` (
  `RoomTypeID` CHAR(10) NOT NULL,
  `RoomType` CHAR(10) NOT NULL,
  `BasePrice` DECIMAL(10) NOT NULL,
  `ExtraPersonID` INT NULL,
  `StandardOccupancy` INT NOT NULL,
  `MaximumOccupancy` INT NOT NULL,
  PRIMARY KEY (`RoomTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`Room` (
  `RoomNumberID` INT NOT NULL,
  `RoomTypeID` CHAR(10) NOT NULL,
  `ADAAccessible` BINARY(2) NOT NULL,
  PRIMARY KEY (`RoomNumberID`),
  INDEX `fk2_idx` (`RoomTypeID` ASC) VISIBLE,
  CONSTRAINT `fk2`
    FOREIGN KEY (`RoomTypeID`)
    REFERENCES `Hotel`.`RoomType` (`RoomTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`Reservation` (
  `ReservationID` INT NOT NULL,
  `RoomNumberID` INT NOT NULL,
  `GuestID` INT NOT NULL,
  `Adults` INT NOT NULL,
  `Children` INT NULL,
  `StartDate` DATETIME NOT NULL,
  `EndDate` DATETIME NOT NULL,
  `TotalRoomCost` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`ReservationID`),
  INDEX `fk_idx` (`GuestID` ASC) VISIBLE,
  INDEX `fk1_idx` (`RoomNumberID` ASC) VISIBLE,
  CONSTRAINT `fk`
    FOREIGN KEY (`GuestID`)
    REFERENCES `Hotel`.`Guest` (`GuestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk1`
    FOREIGN KEY (`RoomNumberID`)
    REFERENCES `Hotel`.`Room` (`RoomNumberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Amenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`Amenities` (
  `AmenitiesID` INT NOT NULL,
  `Amenity` CHAR(20) NOT NULL,
  `Charge` DECIMAL(10) NULL,
  PRIMARY KEY (`AmenitiesID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`RoomTypeAmenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`RoomTypeAmenities` (
  `RoomTypeID` INT NOT NULL,
  `AmenitiesID` INT NOT NULL,
  PRIMARY KEY (`RoomTypeID`, `AmenitiesID`),
  INDEX `fk2_idx` (`AmenitiesID` ASC) VISIBLE,
  CONSTRAINT `fk1`
    FOREIGN KEY (`RoomTypeID`)
    REFERENCES `Hotel`.`RoomType` (`RoomTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2`
    FOREIGN KEY (`AmenitiesID`)
    REFERENCES `Hotel`.`Amenities` (`AmenitiesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
